"""The consistency unit and its fingerprint (AD-15, PDE-11).

Reproducible identity across teams is the **consistency unit**: the Spec, the pinned Profile
artifacts it bundles (each with its own fixed salt), the seed, the pinned dependency versions, and
the fixture set. Two teams that share the same unit produce byte-identical data — and, crucially, a
fingerprint that only matches when the unit truly matches, so a drifted/re-profiled source or a
bumped dependency shows up as a different fingerprint instead of silently mismatched entities.

Almost the whole unit already lives in the Spec: ``Spec.model_dump(mode="json")`` carries the
bundled Profiles, seed, tolerance, shared-key declarations, reserved keyspace blocks, and fixtures.
The only piece outside the Spec is the pinned dependency versions, which we fold in here. The
fingerprint is a stable ``blake2b`` over the canonical JSON of ``{spec, deps}``.
"""

from __future__ import annotations

import hashlib
import json
from importlib.metadata import PackageNotFoundError, version

from tymi.config.spec import Spec

#: Installed packages whose version can shift generated bytes — pinned into the fingerprint.
GENERATION_DEPS = ("tymi", "numpy", "pandas", "faker")


def pinned_deps() -> dict[str, str]:
    """The installed versions of the generation-affecting dependencies (``"unknown"`` if absent)."""
    result: dict[str, str] = {}
    for package in GENERATION_DEPS:
        try:
            result[package] = version(package)
        except PackageNotFoundError:
            result[package] = "unknown"
    return result


def consistency_fingerprint(spec: Spec, *, deps: dict[str, str] | None = None) -> str:
    """A stable hex fingerprint over the consistency unit (AD-15).

    Hashes the canonical JSON of the Spec's dump (bundled Profiles + seed + fixtures + shared-key
    decls) together with the pinned dependency versions. Identical units → identical fingerprints;
    any change to the Spec, a bundled Profile, the seed, the fixtures, or a pinned dep changes it.
    Pass ``deps`` explicitly for a fully reproducible fingerprint independent of the environment;
    by default the live installed versions are read.
    """
    unit = {
        "spec": spec.model_dump(mode="json"),
        "deps": deps if deps is not None else pinned_deps(),
    }
    canonical = json.dumps(unit, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.blake2b(canonical.encode("utf-8"), digest_size=32).hexdigest()
